// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    return $.fn.extend({
      survey: function() {
        var display_question, down, form, i, next, questionContainer, questions, submit, survey, up;
        survey = $('<div>', {
          "class": 'survey-wrapper'
        });
        questionContainer = $('<div>', {
          "class": 'question-container'
        }).appendTo(survey);
        i = 0;
        form = null;
        questions = [];
        next = function() {
          i++;
          console.log(i);
          if (i < questions.length) {
            return display_question();
          } else {
            return submit();
          }
        };
        submit = function() {
          return setTimeout(function() {
            return form.submit();
          }, 500);
        };
        display_question = function() {
          var question;
          question = $('<p>', {
            "class": 'question next'
          });
          question.text(questions[i].text);
          questionContainer.append(question);
          return setTimeout(function() {
            return question.removeClass('next').addClass('active');
          }, 250);
        };
        up = function() {
          $('#' + questions[i].name).attr('checked', true);
          $('.question.active').removeClass('active').addClass('up');
          return next();
        };
        down = function() {
          $('#' + questions[i].name).attr('checked', false);
          $('.question.active').removeClass('active').addClass('down');
          return next();
        };
        return this.each(function() {
          var info, q, text, _i, _len, _ref;
          form = $(this);
          $(this).hide();
          info = $('<div>', {
            "class": 'info'
          });
          $('<span>', {
            "class": 'key up'
          }).text('Ja').appendTo(info);
          $('<span>', {
            "class": 'key down'
          }).text('Nein').appendTo(info);
          info.appendTo(survey);
          _ref = $(this).find('label');
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            q = _ref[_i];
            text = $(q).text();
            questions.push({
              name: $(q).attr('for'),
              text: text
            });
          }
          survey.appendTo($('body'));
          display_question();
          return $(document).on("keydown", function(e) {
            if (e.keyCode === 38) {
              up();
              return false;
            }
            if (e.keyCode === 40) {
              down();
              return false;
            }
          });
        });
      }
    });
  })(jQuery);

}).call(this);

//# sourceMappingURL=survey.map
